### ISSUE TITLE
Put "requires C++17" with variant and optional utilities support

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [p-ranav/tabulate#26]
Modern C++ is C++17 however on the internet "modern" is synonymous with C++11 at minimum. I didn't see any notes anywhere trying to compile but `#include <variant>` and `#include <optional>` gave it away...

On that same note, my mingw tools for gcc on windows have the std::optional utility under `experimental/*`.

I don't think there's a substitute for variant under experimental but a way to be able to swap it out (and optional too) for a custom structures could be achieved for those < C++17. Variants and optional are very simple structures. They're not fundamentally difficult to write and would open the lib up to C++14 at least.

**Comment by jfalcou** [comment]
AFAICS, the variant is used to pass values to the various add_row function. I think that, unless there is a real need for that, add_row can be made fully template OR just plain overloaded on string and table.

If typing is important, the full template version could be implemented with a static_assert checking the types going in are correct. 

@p-ranav what do you think of this stance ?

**Comment by p-ranav** [comment]
The reason to use `variant` there was to be able to write: 

```cpp
table.add_row({"string1", table2, "string3"});

// with extensions in the future to support:
// -> table.add_row({"string1", table2, "string3", row4, cell5, table6[4]});
// which can be used to reuse rows & cells across tables.
```

A simplifying solution here is change the API to simply take `vector<string>` and the usage will change to:

```cpp
table.add_row({"string1", table2.str(), "string3"});
```

.. which is only slightly more verbose. 

I'd like to avoid this change though if there is an elegant template-based solution to this that keeps the client-facing API the same while removing the need for `<variant>`.  

Can you elaborate on that full-template version?

**Comment by DBJDBJ** [comment]
@p-ranav word of advice if I may. This is an open-source project. If anybody thinks she/he has an obvious improvement, it is simple: just fork and do it.

Perhaps (not always) decoupling core and API might be feasible. So that wellwisher can develop their own "better" API, in the peace of their forks.

**Comment by jfalcou** [comment]
A possible C++11 variant less implementation for add_row could be :
https://gist.github.com/jfalcou/961830b5101e7adf32bc4667d3eef53b

This makes calls to add_row lose their {}.
The ugly ass shenanigan around initializer_list is to emulate C++17 fold expression.

Regardless of if such a change is warranted, I would advise you to use std::visit instead of holds_alternatives on your variant.

**Comment by p-ranav** [comment]
I've updated `tabulate` to support `>=C++11` by using variant-lite and optional-lite as fallback data structures if `std::variant` and `std::optional` are not available.
